sonar.projectKey=DistributedTwoPhaseCommitSimulator
sonar.projectName=DistributedTwoPhaseCommitSimulator
sonar.projectVersion=1.0

sonar.sources=\
  backend/coordinator/src/main,\
  backend/participant/src/main,\
  backend/common/src/main,\
  frontend/src

sonar.tests=\
  backend/coordinator/src/test,\
  backend/participant/src/test,\
  backend/common/src/test,\
  frontend/src/test

sonar.test.inclusions=\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx

sonar.java.binaries=\
  backend/coordinator/target/classes,\
  backend/participant/target/classes,\
  backend/common/target/classes

sonar.java.libraries=\
  backend/coordinator/target/dependency/*.jar,\
  backend/participant/target/dependency/*.jar,\
  backend/common/target/dependency/*.jar

sonar.coverage.jacoco.xmlReportPaths=\
  backend/coordinator/target/site/jacoco/jacoco.xml,\
  backend/participant/target/site/jacoco/jacoco.xml,\
  backend/common/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=\
  **/target/**,\
  **/node_modules/**,\
  frontend/src/main.tsx,\
  frontend/src/test/**,\
  frontend/tailwind.config.js,\
  frontend/postcss.config.js

sonar.cpd.exclusions=**/dto/**,**/enums/**,**/types/**

sonar.scm.provider=git
sonar.scanner.trustAllCertificates=true
